version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    deploy:
      resources:
        limits:
          cpus: '1'
    container_name: container_API
